import { useState } from 'react';
import axios from 'axios';

const HabitForm = () => {
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const newHabit = {
      id: '', // Will be generated by the backend
      name,
      description,
      completed: false,
      created_at: new Date().toISOString(),
    };

    try {
      await axios.post('http://127.0.0.1:8080/habits', newHabit);
      setName('');
      setDescription('');
    } catch (error) {
      console.error('Error adding habit:', error);
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      <h2>Add a New Habit</h2>
      <input
        type="text"
        value={name}
        onChange={(e) => setName(e.target.value)}
        placeholder="Habit name"
        required
      />
      <textarea
        value={description}
        onChange={(e) => setDescription(e.target.value)}
        placeholder="Habit description"
        required
      />
      <button type="submit">Add Habit</button>
    </form>
  );
};

export default HabitForm;
